default:
  db: local_sqlite
  llm: openai_prod

db_connections:
  local_sqlite:
    type: "sqlite"     
    path: "test.db"    

  dev_postgres:
    type: "postgres"
    host: "localhost"
    port: 5432
    user: "admin"
    password: "password"
    dbname: "analytics_db"

  prod_mariadb:
    type: "mariadb"
    host: "prod.mariadb.com"
    user: "admin"
    password: "${MARIADB_PASSWORD}"
    dbname: "production_db"

llm_providers:
  openai_prod:
    provider: "openai"  
    model: "gpt-4o-mini"

  local_ollama:
    provider: "ollama"
    model: "granite3.3:2b"
    host: "http://localhost:11434"

  google_gemini:
    provider: "google"
    model: "gemini-2.5-flash"